workflows:
  android-release-apk:
    name: Android Release APK
    max_build_duration: 60
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build debug APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    publishing:
      email:
        recipients:
          - hofmannd404@gmail.com
        notify:
          success: true
          failure: true
